# 파라미터와 하이퍼파라미터
- `parameter`: 모델이 학습하면서 경사하강법으로 값을 바꾸는 부분
    - weight(가중치)
    - bias(편향)   
    ...
- `hyperparameter`: 사람이 정해주는 부분
    - context length
    - 레이어 개수
    - 레이어 당 뉴런 개수
    - 활성화 함수 종류   
    ...

# 토큰
> 언어 모델이 다루는 입출력 단위

- 저희 수업에서는 알파벳 한글자(`a`~`z`)가 한 토큰입니다.   
- 요즘 모델(LLM)들은 더 큰 덩어리가 한 토큰입니다. (`hello`, `안녕` 등)   
- 특별한 뜻을 담은 스페셜 토큰도 있죠! (`문장의 시작`, `문장의 끝` 등)

# Vocabulary
> 언어 모델이 가진 토큰 집합 (어휘집)   

지난 시간에 만들었던 `itos`, `stoi`입니다.

```
{1: 'a',
 2: 'b',
 3: 'c',
 4: 'd',
 5: 'e',
 6: 'f',
 7: 'g',
 8: 'h',
 9: 'i',
 10: 'j',
 11: 'k',
 12: 'l',
 13: 'm',
 14: 'n',
 15: 'o',
 16: 'p',
 17: 'q',
 18: 'r',
 19: 's',
 20: 't',
 21: 'u',
 22: 'v',
 23: 'w',
 24: 'x',
 25: 'y',
 26: 'z',
 0: '.'}
```
(27개)

요즘 모델들은 10,000개 이상의 더 큰 vocab을 가집니다. 

# torch broadcasting
> 특정 연산에서 텐서 모양이 달라도 맞춰줌

- 덧셈, 뺄셈
- 원소간 곱셈, 나눗셈

In [1]:
import torch

In [2]:
a = torch.tensor([1,2,3])
b = torch.tensor([4])
a,b

(tensor([1, 2, 3]), tensor([4]))

In [3]:
a + b # 4를 복제함 -> [1+4, 2+4, 3+4]

tensor([5, 6, 7])

In [ ]:
a * b # 4를 복제함 -> [1*4, 2*4, 3*4]

tensor([ 4,  8, 12])

: 