In [1]:
import torch

# torch dim
> 텐서의 차원 방향!

(`numpy`에서는 `axis`라고 하죠)

## 2차원 텐서

In [2]:
# 2x2 크기 텐서
a = torch.tensor([[1,2], [3,4]]) # 또는 a = torch.arange(1,5).view(2,2) 

print(a.shape)
a

torch.Size([2, 2])


tensor([[1, 2],
        [3, 4]])

In [3]:
a.sum() # 1 + 2 + 3 + 4

tensor(10)

In [4]:
a.sum(dim=0) # 행이 증가하는 방향 [1+3, 2+4]

tensor([4, 6])

In [5]:
a.sum(dim=1) # 열이 증가하는 방향 [1+2, 3+4]

tensor([3, 7])

## 3차원 텐서 (참고용)

In [6]:
# 2x2x2 크기 텐서
b = torch.tensor([[[1,2], [3,4]], [[5,6], [7,8]]]) # 또는 b = torch.arange(1,9).view(2,2,2)

print(b.shape)
b

torch.Size([2, 2, 2])


tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

In [7]:
b.sum()

tensor(36)

In [8]:
b.sum(dim=0)

tensor([[ 6,  8],
        [10, 12]])

In [9]:
b.sum(dim=1)

tensor([[ 4,  6],
        [12, 14]])

In [10]:
b.sum(dim=2)

tensor([[ 3,  7],
        [11, 15]])

## 4차원 텐서 (참고용)

In [11]:
# 2x2x2x2 크기 텐서
c = torch.arange(1,17).view(2,2,2,2)

print(c.shape)
c

torch.Size([2, 2, 2, 2])


tensor([[[[ 1,  2],
          [ 3,  4]],

         [[ 5,  6],
          [ 7,  8]]],


        [[[ 9, 10],
          [11, 12]],

         [[13, 14],
          [15, 16]]]])

In [12]:
c.sum()

tensor(136)

In [13]:
c.sum(dim=0)

tensor([[[10, 12],
         [14, 16]],

        [[18, 20],
         [22, 24]]])

In [14]:
c.sum(dim=1)

tensor([[[ 6,  8],
         [10, 12]],

        [[22, 24],
         [26, 28]]])

In [15]:
c.sum(dim=2)

tensor([[[ 4,  6],
         [12, 14]],

        [[20, 22],
         [28, 30]]])

In [16]:
c.sum(dim=3)

tensor([[[ 3,  7],
         [11, 15]],

        [[19, 23],
         [27, 31]]])

# torch broadcasting
> 특정 연산에서 텐서 모양이 달라도 맞춰줌

- 덧셈, 뺄셈
- 원소간 곱셈, 나눗셈

In [17]:
a = torch.tensor([1,2,3])
b = torch.tensor([4])
a,b

(tensor([1, 2, 3]), tensor([4]))

In [18]:
a + b # 4를 복제함 -> [1+4, 2+4, 3+4]

tensor([5, 6, 7])

In [19]:
a * b # 4를 복제함 -> [1*4, 2*4, 3*4]

tensor([ 4,  8, 12])

# 행렬곱
> 두 행렬끼리 여러 내적(선형조합)을 통해 새 행렬을 만드는 연산

하는 역할들이 정말 많습니다. (참고용으로 알아두죠!)
- 기하학적으로 선형변환(회전, 스케일링)
- 가중합(weighted sum)
- 인공신경망에서 다음 레이어에 정보 전달
- 병렬 처리
- 연립방정식 표현

$A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6\end{bmatrix}$

$B = \begin{bmatrix} 1 & 2 \\ 3 & 4 \\ 5 & 6\end{bmatrix}$

$C = AB = \begin{bmatrix} 1\cdot 1 + 2\cdot 3 + 3\cdot 5 & 1\cdot 2 + 2\cdot 4 + 3\cdot 6 \\ 4\cdot 1 + 5\cdot 3 + 6\cdot 5 & 4\cdot 2 + 5\cdot 4 + 6\cdot 6 \end{bmatrix} = \begin{bmatrix} 22 & 28 \\ 49 & 64 \end{bmatrix}$

In [21]:
A = torch.arange(1,7).view(2,3)
B = torch.arange(1,7).view(3,2)

A,B

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 tensor([[1, 2],
         [3, 4],
         [5, 6]]))

In [23]:
C = A @ B # (2x3) @ (3x2) --> (2x2)
C

tensor([[22, 28],
        [49, 64]])

In [24]:
D = torch.arange(1,13).view(2,2,3)
D

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [25]:
D @ B # (2x2x3) @ (3x2) --> (2x2x2)

tensor([[[ 22,  28],
         [ 49,  64]],

        [[ 76, 100],
         [103, 136]]])

# torch.multinomial
> 다항분포에서 표본 뽑기

말이 어렵긴 한데, 확률 뽑기 기계를 한번 생각해볼게요.   
돌림판에는 상품이 **여러개** 있는데, (다항분포의 **다항**)
- `아이폰` (확률 35%)
- `맥북` (확률 20%)
- `아이패드` (확률 45%)

중에 무조건 하나가 나오고   
여러번 시도하면 여러 개가 나오는 행복한 상상을 해보겠습니다.

3번 시도했을 때,   
`아이폰`, `맥북`, `아이폰` 이렇게 나올 수도 있고   
`아이패드`, `아이패드`, `아이패드` 이렇게 뽑힐 수도 있겠죠?

In [28]:
prizes = ['아이폰', '맥북', '아이패드']
probability = torch.tensor([0.35, 0.20, 0.45])

In [ ]:
# 이 셀을 실행할 때마다 다르게 나옵니다
ix = torch.multinomial(probability, num_samples=3, replacement=True)
', '.join(prizes[i] for i in ix.tolist())

'아이폰, 맥북, 아이패드'

: 